"""Deterministic table of contents generated from the outline (never by the agent)."""

from __future__ import annotations

from pathlib import Path

from fidus.config.outline import Outline

LEVEL_BADGE = {"fundamentals": "🟢", "intermediate": "🟡", "advanced": "🔴"}


def render_index(outline: Outline) -> str:
    lines = [
        "<!-- Generated by Fidus from fidus.outline.yaml. Do not edit by hand; edit the outline. -->",
        "",
        f"# {outline.title}",
        "",
    ]
    if outline.description:
        lines += [outline.description, ""]
    lines += ["Levels: 🟢 fundamentals · 🟡 intermediate · 🔴 advanced", ""]
    current = None
    for n in outline.numbered():
        if n.part.id != current:
            current = n.part.id
            lines += ["", f"## {n.part.title}", ""]
        c = n.chapter
        summary = f" — {c.summary}" if c.summary else ""
        lines.append(f"{n.number}. {LEVEL_BADGE[c.level]} [{c.title}]({c.path}){summary}")
    return "\n".join(lines).rstrip() + "\n"


def index_needs_update(outline: Outline, docs_root: Path, index_file: str | None) -> bool:
    """True when the generated TOC is missing or out of date (e.g. a human edited the outline)."""
    if not index_file or not docs_root.exists():
        return False
    path = docs_root / index_file
    return not path.exists() or path.read_text(encoding="utf-8") != render_index(outline)


def write_index(outline: Outline, docs_root: Path, index_file: str | None) -> bool:
    """Write the index; return True if it changed."""
    if not index_file:
        return False
    path = docs_root / index_file
    content = render_index(outline)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True
