from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest
from typer.testing import CliRunner

from fidus.cli.app import app as cli
from fidus.errors import NotBootstrappedError
from fidus.pipeline.bootstrap import bootstrap
from fidus.pipeline.run import run
from fidus.pipeline.session import Options
from tests.conftest import commit, git

runner = CliRunner()


def test_bootstrap_then_sync_dry_run(project: dict[str, Path]) -> None:
    cfg, root = project["config"], project["root"]
    out1 = root / "out1"
    rep = bootstrap(Options(cfg, dry_run=True, output=out1))
    assert sorted(rep.changed_chapters) == ["auth", "data-model", "overview"]
    assert (out1 / "docs/README.md").read_text().startswith("<!-- Generated by Fidus")
    assert "Fidus bootstrap" in (out1 / "pr-body.md").read_text()
    # dry run never touches the real docs repo
    assert not (project["docs"] / "docs").exists()

    # "Merge" the bootstrap PR by copying its output into the docs repo.
    shutil.copytree(out1 / "docs", project["docs"] / "docs")
    (project["docs"] / ".fidus").mkdir()
    shutil.copy(out1 / "state.json", project["docs"] / ".fidus/state.json")
    git(project["docs"], "add", "-A")
    git(project["docs"], "commit", "-qm", "merge bootstrap")

    # Nothing changed upstream -> no-op.
    assert run(Options(cfg, dry_run=True, output=root / "noop")).noop

    commit(
        project["app"],
        {"src/auth/login.py": "def login(user, ttl=1):\n    return True\n"},
        "feat: ttl",
    )
    commit(project["app"], {"tools/gen.py": "print(1)\n"}, "chore: tooling")
    out2 = root / "out2"
    rep = run(Options(cfg, dry_run=True, output=out2))
    assert rep.changed_chapters == ["auth"]
    state = json.loads((out2 / "state.json").read_text())
    statuses = {t["title"]: t["status"] for t in state["pending"]["triggers"]}
    assert statuses == {"feat: ttl": "applied", "chore: tooling": "unmapped"}
    body = (out2 / "pr-body.md").read_text()
    assert "Needs attention" in body and "app:tools/gen.py" in body
    assert "+- touched `app:src/auth/login.py`" in (out2 / "diff.patch").read_text()
    run_json = json.loads((out2 / "run.json").read_text())
    assert run_json["episodes"][0]["chapter_id"] == "auth"


def test_run_requires_bootstrap_or_since(project: dict[str, Path]) -> None:
    with pytest.raises(NotBootstrappedError):
        run(Options(project["config"], dry_run=True, output=project["root"] / "o"))


def test_audit_mode_checks_every_chapter(project: dict[str, Path]) -> None:
    out = project["root"] / "boot"
    bootstrap(Options(project["config"], dry_run=True, output=out))
    shutil.copytree(out / "docs", project["docs"] / "docs")
    (project["docs"] / ".fidus").mkdir()
    shutil.copy(out / "state.json", project["docs"] / ".fidus/state.json")
    rep = run(
        Options(project["config"], dry_run=True, output=project["root"] / "audit"), mode="audit"
    )
    assert rep.did_audit and not rep.did_sync
    assert {e.chapter_id for e in rep.episodes} == {"overview", "data-model", "auth"}
    state = json.loads((project["root"] / "audit/state.json").read_text())
    assert state["pending"]["audit"]["chapters_checked"] == ["auth", "data-model", "overview"]


def test_cli_commands(project: dict[str, Path]) -> None:
    cfg = str(project["config"])
    res = runner.invoke(cli, ["--version"])
    assert res.exit_code == 0 and "fidus" in res.output
    res = runner.invoke(cli, ["validate", "-c", cfg, "--offline"])
    assert res.exit_code == 0, res.output
    res = runner.invoke(cli, ["validate", "-c", cfg, "--offline", "--strict"])
    assert res.exit_code == 2  # chapters not written yet is a warning
    res = runner.invoke(
        cli, ["run", "-c", cfg, "--dry-run", "--output", str(project["root"] / "x")]
    )
    assert res.exit_code == 1 and "bootstrap" in res.output
    res = runner.invoke(
        cli,
        [
            "run",
            "-c",
            cfg,
            "--dry-run",
            "--since",
            "2020-01-01",
            "--output",
            str(project["root"] / "y"),
        ],
    )
    assert res.exit_code == 0, res.output
    res = runner.invoke(cli, ["doctor", "-c", cfg])
    assert res.exit_code == 0, res.output


def test_init_writes_config_and_outline(tmp_path: Path, project: dict[str, Path]) -> None:
    docs = tmp_path / "newdocs"
    docs.mkdir()
    res = runner.invoke(
        cli,
        [
            "init",
            "-c",
            str(docs / "fidus.yaml"),
            "-s",
            str(project["app"]),
            "--provider",
            "fake",
            "-y",
            "--write-workflow",
        ],
    )
    assert res.exit_code == 0, res.output
    assert (docs / "fidus.outline.yaml").exists()
    assert "create-github-app-token" in (docs / ".github/workflows/fidus.yml").read_text()
    res = runner.invoke(cli, ["validate", "-c", str(docs / "fidus.yaml"), "--offline"])
    assert res.exit_code == 0, res.output


def test_local_cursor_commit_rewritten_falls_back_to_timestamp(
    project: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Production path: state has cursor_sha; if that commit vanished, don't replay history."""
    out = project["root"] / "boot"
    bootstrap(Options(project["config"], dry_run=True, output=out))
    state = json.loads((out / "state.json").read_text())
    state["base"]["repos"]["local:app"]["cursor_sha"] = "0" * 40  # rewritten away
    (project["docs"] / ".fidus").mkdir()
    (project["docs"] / ".fidus/state.json").write_text(json.dumps(state))
    shutil.copytree(out / "docs", project["docs"] / "docs")
    rep = run(Options(project["config"], dry_run=True, output=project["root"] / "o2"))
    assert rep.triggers_collected == 0  # the initial commit predates the cursor timestamp
    monkeypatch.setenv("GIT_COMMITTER_DATE", "2099-01-01T00:00:00+00:00")
    commit(project["app"], {"src/db/models.py": "class M:\n    x: int\n"}, "feat: x")
    rep = run(Options(project["config"], dry_run=True, output=project["root"] / "o3"))
    assert rep.triggers_collected == 1  # only the new commit, not a replay of history


def test_init_force_keeps_config_and_regenerates_outline(project: dict[str, Path]) -> None:
    cfg = project["config"]
    before = cfg.read_text()
    res = runner.invoke(cli, ["init", "-c", str(cfg), "-y", "--force"])
    assert res.exit_code == 0, res.output
    assert cfg.read_text() == before
    assert "Project Handbook" in (project["docs"] / "fidus.outline.yaml").read_text()


def test_init_repairs_low_coverage_outline(tmp_path: Path, project: dict[str, Path]) -> None:
    docs = tmp_path / "cov"
    docs.mkdir()
    res = runner.invoke(
        cli,
        [
            "init",
            "-c",
            str(docs / "fidus.yaml"),
            "-s",
            str(project["app"]),
            "--provider",
            "fake",
            "-y",
        ],
    )
    assert res.exit_code == 0, res.output
    outline = (docs / "fidus.outline.yaml").read_text()
    # The heuristic outline only covers app:src/**; README.md at the root triggers the repair.
    assert "id: misc" in outline and "app:README.md" in outline


def test_init_skips_repair_when_coverage_is_enough(
    tmp_path: Path, project: dict[str, Path]
) -> None:
    docs = tmp_path / "nocov"
    docs.mkdir()
    (docs / "fidus.yaml").write_text(
        f"sources: [{{path: {project['app']}, alias: app}}]\nllm: {{provider: fake}}\n"
        "limits: {init_coverage_target: 0.5}\n"
    )
    res = runner.invoke(cli, ["init", "-c", str(docs / "fidus.yaml"), "-y"])
    assert res.exit_code == 0, res.output
    assert "id: misc" not in (docs / "fidus.outline.yaml").read_text()


def test_triage_cache_skips_repeat_calls(
    project: dict[str, Path], monkeypatch: pytest.MonkeyPatch
) -> None:
    import fidus.pipeline.run as runmod
    from fidus.llm.types import Usage

    out = project["root"] / "boot"
    bootstrap(Options(project["config"], dry_run=True, output=out))
    shutil.copytree(out / "docs", project["docs"] / "docs")
    (project["docs"] / ".fidus").mkdir()
    shutil.copy(out / "state.json", project["docs"] / ".fidus/state.json")
    commit(project["app"], {"tools/gen.py": "print(1)\n"}, "chore: tooling")
    calls: list[list[str]] = []

    def spy(files, *a, **k):  # type: ignore[no-untyped-def]
        calls.append(list(files))
        return {f: None for f in files}, Usage()  # confident "no documentation impact"

    monkeypatch.setattr(runmod, "triage", spy)
    run(Options(project["config"], dry_run=True, output=project["root"] / "r1"))
    assert calls == [["app:tools/gen.py"]]
    state = json.loads((project["root"] / "r1/state.json").read_text())
    assert "app:tools/gen.py" in state["base"]["triage_cache"]["entries"]
    # Deferred (no PR opened): "merge" only the cache and run again -> no second triage call.
    shutil.copy(project["root"] / "r1/state.json", project["docs"] / ".fidus/state.json")
    run(Options(project["config"], dry_run=True, output=project["root"] / "r2"))
    assert len(calls) == 1
